export const translations = {
  ar: {
    // General
    appName: 'COLDSTORE',
    appSubtitle: 'مدير مخزن التبريد',
    loading: 'جاري التحميل...',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    confirm: 'تأكيد',
    close: 'إغلاق',
    refresh: 'تحديث',
    export: 'تصدير',
    print: 'طباعة',
    back: 'رجوع',
    actions: 'الإجراءات',
    notes: 'ملاحظات',
    date: 'التاريخ',
    status: 'الحالة',
    unit: 'الوحدة',
    quantity: 'الكمية',
    details: 'تفاصيل',
    noData: 'لا توجد بيانات',
    noResults: 'لا نتائج مطابقة',
    required: 'مطلوب',
    optional: 'اختياري',
    switchLanguage: 'English',
    switchingLanguage: 'جاري تغيير اللغة...',

    // Auth
    signIn: 'تسجيل الدخول',
    signInTo: 'تسجيل الدخول إلى حسابك',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    emailPlaceholder: 'example@company.com',
    passwordPlaceholder: 'أدخل كلمة المرور',
    contactAdmin: 'تواصل مع المدير للحصول على وصول',
    signingIn: 'جاري الدخول...',

    // Welcome
    welcomeTo: 'مرحباً بك في',
    hello: 'أهلاً،',
    loadingData: 'جاري تحميل البيانات...',

    // Nav
    dashboard: 'لوحة التحكم',
    clients: 'العملاء',
    operations: 'العمليات',
    inventory: 'المخزون',
    scanNow: 'مسح الباركود',
    signOut: 'تسجيل الخروج',

    // Dashboard
    dashboardSubtitle: 'نظرة عامة على مخزن التبريد',
    totalClients: 'إجمالي العملاء',
    registeredClients: 'عميل مسجل',
    currentInventory: 'المخزون الحالي',
    activeBatchesStock: 'إجمالي الشحنات النشطة',
    todayOps: 'عمليات اليوم',
    inOutToday: 'دخول وخروج اليوم',
    activeBatches: 'الشحنات النشطة',
    activeBatchesDesc: 'شحنة نشطة أو جزئية',
    readyAnytime: 'جاهزة للخروج في أي وقت',
    quickLinks: 'روابط سريعة',
    registerIncoming: 'تسجيل بضاعة واردة',
    registerOutgoing: 'تسجيل بضاعة صادرة',
    viewInventory: 'عرض المخزون',
    live: 'مباشر',

    // Clients
    clientsSubtitle: 'عميل مسجل',
    addClient: 'إضافة عميل',
    clientName: 'الاسم',
    clientPhone: 'الهاتف',
    clientNotes: 'ملاحظات',
    registeredDate: 'تاريخ التسجيل',
    searchClients: 'بحث بالاسم أو الهاتف...',
    editClient: 'تعديل عميل',
    deleteClient: 'حذف عميل',
    deleteClientConfirm: 'هل تريد حذف',
    deleteClientWarn: 'لا يمكن التراجع.',
    namePlaceholder: 'اسم العميل',
    phonePlaceholder: '+20 xxx xxx xxxx',
    notesPlaceholder: 'ملاحظات إضافية...',
    nameRequired: 'الاسم مطلوب',
    saving: 'جاري الحفظ...',
    saveChanges: 'حفظ التغييرات',
    noPhone: 'لا يوجد هاتف',

    // Client Detail
    totalOps: 'إجمالي العمليات',
    totalIn: 'إجمالي الدخول',
    totalOut: 'إجمالي الخروج',
    units: 'وحدة',
    allProducts: 'كل المنتجات',
    product: 'المنتج',
    fromDate: 'من تاريخ',
    toDate: 'إلى تاريخ',
    applyFilter: 'بحث',
    resetFilter: 'إعادة تعيين',
    exportPdf: 'تصدير PDF',
    batchCode: 'كود الشحنة',
    dateTime: 'التاريخ والوقت',
    typeIn: '↓ دخول',
    typeOut: '↑ خروج',
    noTransactions: 'لا توجد تعاملات',
    statementTitle: 'كشف حساب',
    statementClient: 'العميل',
    statementPhone: 'الهاتف',
    statementPrinted: 'تاريخ الطباعة',
    statementTotal: 'إجمالي العمليات',
    statementFooter: 'تم الإنشاء بواسطة COLDSTORE System',

    // Operations
    operationsSubtitle: 'تسجيل دخول وخروج البضائع',
    inMode: '↓ دخول IN',
    outMode: '↑ خروج OUT',
    inDesc: 'تسجيل بضاعة واردة — سيتم إنشاء Batch جديد',
    outDesc: 'تسجيل بضاعة صادرة — اختر شحنة من الموجود',
    selectClient: 'اختر عميل...',
    selectProduct: 'اختر منتج...',
    quantityPlaceholder: '0.00',
    kg: 'كيلو',
    ton: 'طن',
    notesOptional: 'ملاحظات اختيارية...',
    registerIn: '📥 تسجيل الدخول',
    confirmOut: '📤 تأكيد الخروج',
    processingDots: 'جاري الحفظ...',
    allFieldsRequired: 'جميع الحقول مطلوبة',
    quantityPositive: 'الكمية يجب أن تكون أكبر من صفر',
    selectBatch: 'الشحنة (Batch) *',
    noBatches: 'لا توجد شحنات نشطة لهذا العميل',
    remaining: 'متبقي',
    outQtyLabel: 'الكمية الخارجة *',
    outNotesPlaceholder: 'مثال: تسليم للعميل، بضاعة تالفة...',
    recentBatches: 'آخر الشحنات',
    original: 'الكمية الأصلية',
    enterQty: 'أدخل الكمية',
    qtyTooLarge: 'الكمية أكبر من المتاح',
    clientRequired: 'اختر عميل أولاً',
    batchRequired: 'اختر شحنة أولاً',

    // Batch Status
    statusActive: 'نشطة',
    statusPartial: 'جزئية',
    statusClosed: 'مقفلة',

    // Print
    batchRegistered: '✅ تم تسجيل الشحنة',
    printCard: '🖨️ طباعة البطاقة',
    client: 'العميل',
    createdBy: 'تم الإنشاء بواسطة COLDSTORE System',
    facilityName: 'COLD STORAGE FACILITY',
    batchCodeLabel: 'كود الشحنة / Batch Code',
    statusLabel: 'نشطة ✓',

    // Out Confirm Modal
    confirmOutTitle: 'تأكيد عملية الخروج',
    outDetails: 'تفاصيل الخروج',
    outQtyLabel2: 'الكمية الخارجة',
    originalQty: 'الكمية الأصلية',
    remainingAfter: 'المتبقي بعد الخروج',
    fullOut: 'خروج كامل للشحنة 🔒',
    note: 'ملاحظة',
    confirmAndScan: 'تأكيد ومسح الباركود ←',
    scanWarning: '⚠️ بعد التأكيد ستحتاج لمسح باركود الشحنة خلال 60 ثانية لإتمام العملية',
    scanTitle: 'امسح باركود الشحنة',
    scanDesc: 'وجّه الجهاز على باركود الكود:',
    timeRemaining: 'الوقت المتبقي للتأكيد',
    scanPlaceholder: 'امسح أو اكتب الكود يدوياً...',
    processingOp: 'جاري المعالجة...',
    cancelOp: 'إلغاء العملية',
    codeMismatch: 'الكود غير مطابق! المتوقع:',
    successTitle: 'تمت العملية بنجاح!',
    successDesc: 'تم تسجيل خروج',
    successFrom: 'من الشحنة',
    timeoutTitle: 'انتهت مهلة التأكيد',
    timeoutDesc: 'لم يتم مسح الباركود في الوقت المحدد.',
    noOpRegistered: 'لم تُسجَّل أي عملية.',
    dataKept: 'بياناتك محفوظة، يمكنك المحاولة مجدداً.',
    timeoutBanner: 'فشل تأكيد الخروج — الشحنة',
    timeoutBanner2: 'لا تزال في المخزون',
    retryBtn: '← العودة وإعادة المحاولة',

    // Scan Page
    scanPageTitle: 'مسح الباركود',
    scanPageSubtitle: 'مسح باركود للخروج السريع',
    openCamera: '📷 فتح الكاميرا',
    closeCamera: '✕ إغلاق الكاميرا',
    orManual: 'أو أدخل الكود يدوياً',
    scanInputPlaceholder: 'FRZ-000001',
    searchBtn: '🔍 بحث',
    notFound: 'لم يتم العثور على شحنة بالكود:',
    batchClosed: 'الشحنة مقفلة — تم تفريغها بالكامل',
    scanAnother: '← مسح آخر',
    progressRemaining: 'المتبقي',

    // Inventory
    inventorySubtitle: 'الشحنات النشطة في المخزن',
    totalInventory: 'إجمالي المخزون',
    activeBatchesCount: 'شحنات نشطة',
    partialBatches: 'شحنات جزئية',
    searchInventory: 'بحث بالعميل أو المنتج أو الكود...',
    noInventory: 'المخزن فارغ',
    entryDate: 'تاريخ الدخول',
  },

  en: {
    appName: 'COLDSTORE',
    appSubtitle: 'Cold Storage Facility Manager',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    confirm: 'Confirm',
    close: 'Close',
    refresh: 'Refresh',
    export: 'Export',
    print: 'Print',
    back: 'Back',
    actions: 'Actions',
    notes: 'Notes',
    date: 'Date',
    status: 'Status',
    unit: 'Unit',
    quantity: 'Quantity',
    details: 'Details',
    noData: 'No data available',
    noResults: 'No matching results',
    required: 'Required',
    optional: 'Optional',
    switchLanguage: 'عربي',
    switchingLanguage: 'Switching language...',

    signIn: 'Sign In',
    signInTo: 'Sign in to your account',
    email: 'Email address',
    password: 'Password',
    emailPlaceholder: 'you@company.com',
    passwordPlaceholder: 'Enter your password',
    contactAdmin: 'Contact your administrator if you need access.',
    signingIn: 'Signing in...',

    welcomeTo: 'Welcome to',
    hello: 'Hello,',
    loadingData: 'Loading your data...',

    dashboard: 'Dashboard',
    clients: 'Clients',
    operations: 'Operations',
    inventory: 'Inventory',
    scanNow: 'Scan Now',
    signOut: 'Sign Out',

    dashboardSubtitle: 'Overview of your cold storage facility',
    totalClients: 'Total Clients',
    registeredClients: 'Registered clients',
    currentInventory: 'Current Inventory',
    activeBatchesStock: 'Total active batches in storage',
    todayOps: "Today's Operations",
    inOutToday: 'IN & OUT movements today',
    activeBatches: 'Active Batches',
    activeBatchesDesc: 'Active or partial batches',
    readyAnytime: 'Ready for outgoing at any time',
    quickLinks: 'Quick Links',
    registerIncoming: 'Register Incoming Goods',
    registerOutgoing: 'Register Outgoing Goods',
    viewInventory: 'View Inventory',
    live: 'Live',

    clientsSubtitle: 'registered clients',
    addClient: 'Add Client',
    clientName: 'Name',
    clientPhone: 'Phone',
    clientNotes: 'Notes',
    registeredDate: 'Registered',
    searchClients: 'Search by name or phone...',
    editClient: 'Edit Client',
    deleteClient: 'Delete Client',
    deleteClientConfirm: 'Are you sure you want to delete',
    deleteClientWarn: 'This action cannot be undone.',
    namePlaceholder: 'Client full name',
    phonePlaceholder: '+20 xxx xxx xxxx',
    notesPlaceholder: 'Additional notes...',
    nameRequired: 'Name is required',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    noPhone: 'No phone',

    totalOps: 'Total Operations',
    totalIn: 'Total IN',
    totalOut: 'Total OUT',
    units: 'units',
    allProducts: 'All Products',
    product: 'Product',
    fromDate: 'From Date',
    toDate: 'To Date',
    applyFilter: 'Search',
    resetFilter: 'Reset',
    exportPdf: 'Export PDF',
    batchCode: 'Batch Code',
    dateTime: 'Date & Time',
    typeIn: '↓ IN',
    typeOut: '↑ OUT',
    noTransactions: 'No transactions found',
    statementTitle: 'Account Statement',
    statementClient: 'Client',
    statementPhone: 'Phone',
    statementPrinted: 'Print Date',
    statementTotal: 'Total Operations',
    statementFooter: 'Generated by COLDSTORE System',

    operationsSubtitle: 'Register incoming and outgoing goods',
    inMode: '↓ IN',
    outMode: '↑ OUT',
    inDesc: 'Register incoming goods — A new Batch will be created',
    outDesc: 'Register outgoing goods — Select an existing batch',
    selectClient: 'Select a client...',
    selectProduct: 'Select a product...',
    quantityPlaceholder: '0.00',
    kg: 'KG',
    ton: 'TON',
    notesOptional: 'Optional notes...',
    registerIn: '📥 Register IN',
    confirmOut: '📤 Confirm OUT',
    processingDots: 'Saving...',
    allFieldsRequired: 'All fields are required',
    quantityPositive: 'Quantity must be greater than zero',
    selectBatch: 'Batch *',
    noBatches: 'No active batches for this client',
    remaining: 'Remaining',
    outQtyLabel: 'Outgoing Quantity *',
    outNotesPlaceholder: 'e.g. Client delivery, damaged goods...',
    recentBatches: 'Recent Batches',
    original: 'Original Qty',
    enterQty: 'Enter quantity',
    qtyTooLarge: 'Quantity exceeds available stock',
    clientRequired: 'Please select a client first',
    batchRequired: 'Please select a batch first',

    statusActive: 'Active',
    statusPartial: 'Partial',
    statusClosed: 'Closed',

    batchRegistered: '✅ Batch Registered',
    printCard: '🖨️ Print Card',
    client: 'Client',
    createdBy: 'Generated by COLDSTORE System',
    facilityName: 'COLD STORAGE FACILITY',
    batchCodeLabel: 'Batch Code',
    statusLabel: 'Active ✓',

    confirmOutTitle: 'Confirm OUT Operation',
    outDetails: 'Operation Details',
    outQtyLabel2: 'Outgoing Quantity',
    originalQty: 'Original Quantity',
    remainingAfter: 'Remaining After OUT',
    fullOut: 'Full batch clearance 🔒',
    note: 'Note',
    confirmAndScan: 'Confirm & Scan Barcode →',
    scanWarning: '⚠️ After confirming, you have 60 seconds to scan the barcode to complete the operation',
    scanTitle: 'Scan Batch Barcode',
    scanDesc: 'Point your scanner at the barcode for:',
    timeRemaining: 'Time remaining',
    scanPlaceholder: 'Scan or type code manually...',
    processingOp: 'Processing...',
    cancelOp: 'Cancel Operation',
    codeMismatch: 'Code mismatch! Expected:',
    successTitle: 'Operation Successful!',
    successDesc: 'Successfully registered OUT of',
    successFrom: 'from batch',
    timeoutTitle: 'Confirmation Timeout',
    timeoutDesc: 'Barcode was not scanned in time.',
    noOpRegistered: 'No operation was registered.',
    dataKept: 'Your data is saved. You can try again.',
    timeoutBanner: 'OUT failed — Batch',
    timeoutBanner2: 'is still in storage',
    retryBtn: '← Return & Retry',

    scanPageTitle: 'Scan Barcode',
    scanPageSubtitle: 'Scan barcode for quick outgoing',
    openCamera: '📷 Open Camera',
    closeCamera: '✕ Close Camera',
    orManual: 'Or enter code manually',
    scanInputPlaceholder: 'FRZ-000001',
    searchBtn: '🔍 Search',
    notFound: 'No batch found with code:',
    batchClosed: 'Batch is CLOSED — fully cleared',
    scanAnother: '← Scan Another',
    progressRemaining: 'Remaining',

    inventorySubtitle: 'Active batches in storage',
    totalInventory: 'Total Inventory',
    activeBatchesCount: 'Active Batches',
    partialBatches: 'Partial Batches',
    searchInventory: 'Search by client, product or code...',
    noInventory: 'Storage is empty',
    entryDate: 'Entry Date',
  }
}
